# docker-compose.yml
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    image: ${DOCKERHUB_USERNAME}/three-tier-backend:${TAG}
    environment:
      PORT: 3001
      DATABASE_URL: postgres://postgres:password@db:5432/notes_db
      CORS_ORIGIN: http://74.248.130.191:3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    # wget-based healthcheck (Alpine has busybox wget)
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3001/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  frontend:
    image: ${DOCKERHUB_USERNAME}/three-tier-frontend:${TAG}
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      REACT_APP_API_URL: http://74.248.130.191:3001
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
