services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
  image: ${DOCKERHUB_USERNAME}/three-tier-backend:${TAG}
  environment:
    PORT: 3001
    DATABASE_URL: postgres://postgres:password@db:5432/notes_db
    CORS_ORIGIN: http://74.248.130.191:3000
  depends_on:
    - db
  ports:
    - "3001:3001"
  healthcheck:
    test: ["CMD-SHELL", "wget -qO- http://localhost:3001/health >/dev/null 2>&1 || exit 1"]
    interval: 10s
    timeout: 3s
    retries: 10
    start_period: 20s


  frontend:
    image: ${DOCKERHUB_USERNAME}/three-tier-frontend:${TAG}
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      REACT_APP_API_URL: http://74.248.130.191:3001
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:
