services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: 3001
      # IMPORTANT: host is the service name "db"
      DATABASE_URL: postgres://postgres:password@db:5432/notes_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      # so the browser talks to your backend
      REACT_APP_API_URL: http://localhost:3001
    depends_on: [backend]
    ports:
      - "3000:3000"

volumes:
  db_data:
